url: http://denadev.github.io/wahid
identifier: com.github.denadev.wahid
project:
  name: Wahid
lsi: false
safe: true
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
  parse_block_html: true

